import "./globals.css";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import ThemeProvider from "@/theme/ThemeProvider";
import LayoutPage from "@/components/layout/LayoutPage";

const vazir = Vazirmatn({ subsets: ["latin"], variable: "--font-vazir" });

export const metadata: Metadata = {
  title: "مرکز اموزشی دیجیتال",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.variable}>
        <ThemeProvider>
          <AntdRegistry>
            <LayoutPage children={children} />
          </AntdRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
